name: mi primer github action
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hola cuando hace un push
    - name: docker
      run: docker -v
    - name: build image
      run: docker build . -t fidelmace/gitactnodeimage:240520
    - name: list image
      run: docker images
    - name: pushing to docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        echo 'Docker login'
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        echo 'Sending to hub'
        docker push fidelmace/gitactnodeimage:240520
    - name: pulling from docker hub
      run: docker pull cinthyamontalvo/gitactnodeimage:240520
